### ISSUE TITLE
`tockler` instead?

### ISSUE THREAD

**Issue by efrecon** [cyanogilvie/tcl-docker-client#1]
While not automatically generated, you could have a look at [`tockler`](https://github.com/efrecon/tockler) instead. It *might* fit the bill. Or we could join forces as `tockler` closely follows the API spec for the lower-level definitions.

**Comment by cyanogilvie** [comment]
tockler looks good, thanks.  Unfortunately didn't show up in the search I did for "Tcl docker" before writing this version.  I'll point people at tockler in this project's README.

If anything in the auto generation from the swagger description is helpful to tockler you're of course welcome to incorporate it (very rough so far, hacked it together yesterday: [tcl-openapi](https://github.com/cyanogilvie/tcl-openapi).  I noticed tockler exec's things to talk unix_sockets, but there is native support in Tcl: [unix_sockets](https://github.com/cyanogilvie/unix_sockets), with integration into [rl_http](https://github.com/RubyLane/rl_http), although I admit I'm lousy at letting anyone know about these things.  Also, I'll just point out that there is a very fast way of working with JSON in Tcl: [rl_json](https://github.com/RubyLane/rl_json) ;)

**Comment by efrecon** [comment]
I know about `rl_http` and `rl_json`. Didn't about `unix_sockets`. I wanted `tockler` to be able to run on bare-installs (well, at least with as little cruft as possible). The rubylane libraries are fantastic and you've done a marvellous job at modernising Tcl, but they are a dependency I didn't want to have in order to lower the threshold of entry.

Nowadays, I usually talk to the Docker socket using a [proxy](https://github.com/Tecnativa/docker-socket-proxy) for increased security. It makes using domain sockets a little obsolete.
